import { Hono } from 'hono';
import { bodyLimit } from 'hono/body-limit';
import { z, ZodError } from 'zod';
import { ApiError, type AppEnv, type Env, camel, column, itemSchema } from './model';
import { GoogleVerifier, type GoogleTokenVerifier, issueSession, verifySession } from './auth';
import { BrowserFetcher, ChainFetcher, MirroredFetcher, SimpleFetcher, boundedBody, zozoYahooMirror, type PageFetcher } from './fetcher';
import { classifyProduct, importUrl, reason, searchProducts } from './import';
function pageFetcher(env:Env,url:string):PageFetcher{
 const steps:PageFetcher[]=[new SimpleFetcher()];
 const mirror=zozoYahooMirror(url);
 if(mirror)steps.push(new MirroredFetcher(new SimpleFetcher(),mirror));
 if(env.BROWSER)steps.push(new BrowserFetcher(env.BROWSER));
 return steps.length===1?steps[0]:new ChainFetcher(steps,error=>console.warn('fetch fallback',reason(error)));
}
async function images(env:Env,user:string,id:string){return (await env.DB.prepare('SELECT * FROM item_images WHERE item_id=? AND user_id=? ORDER BY sort_order,created_at').bind(id,user).all()).results.map(camel);}
async function item(env:Env,user:string,id:string){const row=await env.DB.prepare('SELECT * FROM wardrobe_items WHERE id=? AND user_id=?').bind(id,user).first();if(!row)throw new ApiError('NOT_FOUND','服が見つかりません',404);return {...camel(row),images:await images(env,user,id)};}
export function imageType(b:Uint8Array){if(b[0]===255&&b[1]===216&&b[2]===255)return 'image/jpeg';if(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)return 'image/png';if(new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP')return 'image/webp';throw new ApiError('INVALID_IMAGE','JPEG・PNG・WebPを選択してください');}
async function storeImage(env:Env,user:string,bytes:Uint8Array,sourceUrl?:string){const type=imageType(bytes),id=crypto.randomUUID(),url=`/api/images/${id}/original`;await env.IMAGES.put(`${user}/${id}/original`,bytes,{httpMetadata:{contentType:type}});await env.DB.prepare('INSERT INTO item_images(id,user_id,original_url,original_source_url,source,created_at) VALUES(?,?,?,?,?,?)').bind(id,user,url,sourceUrl??null,sourceUrl?'product_url':'upload',new Date().toISOString()).run();return {id,originalUrl:url,processingStatus:'pending'};}
export function createApp(verifier:GoogleTokenVerifier=new GoogleVerifier()){
 const app=new Hono<AppEnv>();
 app.use('*',async(c,next)=>{c.set('requestId',crypto.randomUUID());await next();c.header('X-Request-Id',c.get('requestId'));c.header('X-Content-Type-Options','nosniff');c.header('Cache-Control','no-store');});
 app.use('/api/*',bodyLimit({maxSize:11000000,onError:()=>{throw new ApiError('TOO_LARGE','ファイルが大きすぎます',413);}}));
 app.onError((e,c)=>{const err=e instanceof ZodError?new ApiError('VALIDATION','入力内容を確認してください'):e instanceof ApiError?e:new ApiError('INTERNAL','処理できませんでした。再度お試しください',500);return c.json({error:{code:err.code,message:err.message,requestId:c.get('requestId')}},err.status as 400);});
 app.notFound(c=>c.json({error:{code:'NOT_FOUND',message:'見つかりません',requestId:c.get('requestId')}},404));
 app.get('/health',c=>c.json({ok:true}));
 app.post('/api/auth/google',async c=>{const {idToken}=z.object({idToken:z.string().min(1).max(10000)}).parse(await c.req.json());const g=await verifier.verify(idToken,c.env.GOOGLE_SERVER_CLIENT_ID),now=new Date().toISOString();await c.env.DB.prepare('INSERT INTO users(id,google_sub,email,display_name,photo_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(google_sub) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,photo_url=excluded.photo_url,updated_at=excluded.updated_at').bind(crypto.randomUUID(),g.sub,g.email,g.name??null,g.picture??null,now,now).run();const u=await c.env.DB.prepare('SELECT id,email,display_name,photo_url FROM users WHERE google_sub=?').bind(g.sub).first();if(!u)throw Error();return c.json({token:await issueSession(u.id as string,c.env.SESSION_SECRET),expiresAt:new Date(Date.now()+604800000).toISOString(),user:camel(u)});});
 app.use('/api/*',async(c,next)=>{const auth=c.req.header('Authorization');if(!auth?.startsWith('Bearer '))throw new ApiError('UNAUTHORIZED','ログインしてください',401);const id=await verifySession(auth.slice(7),c.env.SESSION_SECRET);if(!await c.env.DB.prepare('SELECT id FROM users WHERE id=?').bind(id).first())throw new ApiError('UNAUTHORIZED','ログインしてください',401);c.set('userId',id);await next();});
 app.get('/api/auth/me',async c=>c.json({user:camel((await c.env.DB.prepare('SELECT id,email,display_name,photo_url FROM users WHERE id=?').bind(c.get('userId')).first())!)}));
 app.post('/api/auth/logout',c=>c.json({ok:true}));
 app.get('/api/categories',async c=>c.json({categories:(await c.env.DB.prepare('SELECT * FROM categories ORDER BY sort_order').all()).results.map(camel)}));
 app.get('/api/brands',async c=>c.json({brands:(await c.env.DB.prepare('SELECT DISTINCT brand FROM wardrobe_items WHERE user_id=? AND brand IS NOT NULL ORDER BY brand').bind(c.get('userId')).all()).results.map(r=>r.brand)}));
 app.get('/api/items',async c=>{const q=c.req.query(),where=['user_id=?'];const args:unknown[]=[c.get('userId')];for(const f of ['status','category','brand','normalizedColor','sleeve','size'])if(q[f]){where.push(`${column(f)}=?`);args.push(q[f]);}if(q.search){where.push("lower(coalesce(name,'')||' '||coalesce(brand,'')||' '||coalesce(category,'')||' '||coalesce(sub_category,'')||' '||coalesce(original_color,'')||' '||coalesce(normalized_color,'')||' '||coalesce(product_code,'')||' '||coalesce(sku,'')||' '||coalesce(shop_name,'')) LIKE ? ESCAPE '\\'");args.push('%'+q.search.toLowerCase().replace(/[\\%_]/g,'\\$&')+'%');}const sorts:Record<string,string>={recent:'created_at DESC',oldest:'created_at ASC',brand:'brand IS NULL,brand ASC',purchasePrice:'purchase_price IS NULL,purchase_price ASC',listPrice:'list_price IS NULL,list_price ASC'};const rows=await c.env.DB.prepare(`SELECT * FROM wardrobe_items WHERE ${where.join(' AND ')} ORDER BY ${sorts[q.sort]??sorts.recent},id`).bind(...args).all();const imgs=(await c.env.DB.prepare('SELECT * FROM item_images WHERE user_id=? AND item_id IS NOT NULL ORDER BY sort_order,created_at').bind(c.get('userId')).all()).results;return c.json({items:rows.results.map(r=>({...camel(r),images:imgs.filter(i=>i.item_id===r.id).map(camel)}))});});
 app.get('/api/items/:id',async c=>c.json({item:await item(c.env,c.get('userId'),c.req.param('id'))}));
 for(const method of ['post','put'] as const)app[method](method==='post'?'/api/items':'/api/items/:id',async c=>{const input=itemSchema.parse(await c.req.json()),user=c.get('userId'),id=method==='post'?crypto.randomUUID():c.req.param('id');if(method==='put')await item(c.env,user,id);if(input.groupId&&!await c.env.DB.prepare('SELECT id FROM item_groups WHERE id=? AND user_id=?').bind(input.groupId,user).first())throw new ApiError('VALIDATION','グループが見つかりません');const refs=input.images??[...(input.imageIds??[]).map(id=>({id})),...(input.imageUrls??[]).map(url=>({url}))];const ids:string[]=[];for(const ref of refs)if('id' in ref&&ref.id){if(!await c.env.DB.prepare('SELECT id FROM item_images WHERE id=? AND user_id=? AND (item_id IS NULL OR item_id=?)').bind(ref.id,user,id).first())throw new ApiError('VALIDATION','画像を使用できません');ids.push(ref.id);}for(const ref of refs)if('url' in ref&&ref.url){const f=await new SimpleFetcher().get(ref.url,'image');ids.push((await storeImage(c.env,user,f.bytes,ref.url)).id);}if(new Set(ids).size>8)throw new ApiError('VALIDATION','画像は8枚までです');const data=Object.fromEntries(Object.entries(input).filter(([k])=>!['images','imageIds','imageUrls'].includes(k))),now=new Date().toISOString(),keys=Object.keys(data),values=Object.values(data);const stmt=method==='post'?c.env.DB.prepare(`INSERT INTO wardrobe_items(id,user_id,${keys.map(column).join(',')},created_at,updated_at) VALUES(${Array(keys.length+4).fill('?').join(',')})`).bind(id,user,...values,now,now):c.env.DB.prepare(`UPDATE wardrobe_items SET ${keys.map(k=>column(k)+'=?').join(',')},updated_at=? WHERE id=? AND user_id=?`).bind(...values,now,id,user);await c.env.DB.batch([stmt,...ids.map((img,n)=>c.env.DB.prepare('UPDATE item_images SET item_id=?,sort_order=?,is_primary=? WHERE id=? AND user_id=? AND (item_id IS NULL OR item_id=?)').bind(id,n,n===0?1:0,img,user,id))]);return c.json({item:await item(c.env,user,id)},method==='post'?201:200);});
 app.post('/api/items/:id/archive',async c=>{const id=c.req.param('id'),user=c.get('userId');await item(c.env,user,id);await c.env.DB.prepare("UPDATE wardrobe_items SET status='archived',updated_at=? WHERE id=? AND user_id=?").bind(new Date().toISOString(),id,user).run();return c.json({item:await item(c.env,user,id)});});
 app.delete('/api/items/:id',async c=>{const id=c.req.param('id'),user=c.get('userId');await item(c.env,user,id);const imgs=await images(c.env,user,id);await c.env.DB.prepare('DELETE FROM wardrobe_items WHERE id=? AND user_id=?').bind(id,user).run();await Promise.all(imgs.flatMap(i=>['original','display','thumbnail'].map(v=>c.env.IMAGES.delete(`${user}/${i.id}/${v}`))));return c.json({ok:true});});
 app.post('/api/import/url',async c=>{const {url}=z.object({url:z.string().url().max(4096)}).parse(await c.req.json());const preview=await importUrl(url,c.env,pageFetcher(c.env,url));const duplicate=await c.env.DB.prepare('SELECT id FROM wardrobe_items WHERE user_id=? AND source_url=? LIMIT 1').bind(c.get('userId'),preview.sourceUrl).first();return c.json({...preview,duplicate:!!duplicate});});
 app.post('/api/import/search',async c=>{const {name,brand}=z.object({name:z.string().trim().min(1).max(100),brand:z.string().trim().max(60).optional()}).parse(await c.req.json());return c.json(await searchProducts(name,brand,c.env));});
 app.post('/api/classify',async c=>{const {name,brand}=z.object({name:z.string().trim().min(1).max(200),brand:z.string().trim().max(60).optional()}).parse(await c.req.json());return c.json(await classifyProduct(name,brand,c.env));});
 app.post('/api/images',async c=>c.json({image:await storeImage(c.env,c.get('userId'),await boundedBody(new Response(c.req.raw.body),10000000))},201));
 app.get('/api/images/:id/:variant',async c=>{const {id,variant}=c.req.param();if(!['original','display','thumbnail'].includes(variant))throw new ApiError('NOT_FOUND','画像が見つかりません',404);if(!await c.env.DB.prepare('SELECT id FROM item_images WHERE id=? AND user_id=?').bind(id,c.get('userId')).first())throw new ApiError('NOT_FOUND','画像が見つかりません',404);const obj=await c.env.IMAGES.get(`${c.get('userId')}/${id}/${variant}`);if(!obj)throw new ApiError('NOT_FOUND','画像が見つかりません',404);return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType??'image/jpeg','X-Content-Type-Options':'nosniff'}});});
 app.post('/api/images/:id/process',async c=>{const id=c.req.param('id'),user=c.get('userId');if(!await c.env.DB.prepare('SELECT id FROM item_images WHERE id=? AND user_id=?').bind(id,user).first())throw new ApiError('NOT_FOUND','画像が見つかりません',404);const form=await c.req.formData(),status=form.get('status');if(status==='failed'||status==='processing'){await c.env.DB.prepare('UPDATE item_images SET processing_status=? WHERE id=? AND user_id=?').bind(status,id,user).run();return c.json({ok:true});}for(const variant of ['display','thumbnail']){const file=form.get(variant);if(!(file instanceof File)||file.size>5000000)throw new ApiError('VALIDATION','処理済み画像が必要です');const bytes=new Uint8Array(await file.arrayBuffer());await c.env.IMAGES.put(`${user}/${id}/${variant}`,bytes,{httpMetadata:{contentType:imageType(bytes)}});}await c.env.DB.prepare("UPDATE item_images SET processing_status='completed',display_url=?,thumbnail_url=? WHERE id=? AND user_id=?").bind(`/api/images/${id}/display`,`/api/images/${id}/thumbnail`,id,user).run();return c.json({ok:true});});
 return app;
}
export default createApp();
